# .streamlit/secrets.toml

# Everything in this section will be available as an environment variable
db_username = "Jane"
db_password = "12345qwerty"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment
# variables, but they'll be easily accessible from within Streamlit anyway
# as we show later in this doc.
[my_cool_secrets]
things_i_like = ["Streamlit", "Python"]

[mongo]
host = "ac-bkgkvzv-shard-00-01.whxfjnx.mongodb.net"
port = 27017
username = "butsuryudao"
password = "jW2K4yufU8DcbXDC"

